// CONSOLIDATED WORD DATABASE - used by all game modes

const wordDatabase = [
      { en: "Pizza", ku: "پیتزا", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Ocean", ku: "زەریا", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Guitar", ku: "گیتار", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Hospital", ku: "نەخۆشخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "School", ku: "قوتابخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Car", ku: "ئۆتۆمبێل", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Book", ku: "کتێب", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Mountain", ku: "چیا", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Phone", ku: "تەلەفۆن", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Coffee", ku: "قاوە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Man", ku: "پیاو", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Woman", ku: "ژن", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Child", ku: "منداڵ", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Father", ku: "باوک", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Mother", ku: "دایک", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Brother", ku: "برا", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Sister", ku: "خوشک", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Friend", ku: "هاوڕێ", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Teacher", ku: "مامۆستا", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Doctor", ku: "دکتۆر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Student", ku: "قوتابی", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Baby", ku: "منداڵى ساوا", hint: { en: "Person/Family", ku: "کەس" } },
      { en: "Grandfather", ku: "باپیر", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Grandmother", ku: "دایەگەورە", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Neighbor", ku: "دراوسێ", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Stranger", ku: "بێگانە", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Engineer", ku: "ئەندازیار", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Pilot", ku: "فڕۆکەوان", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Soldier", ku: "سەرباز", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Cook/Chef", ku: "چێشتلێنەر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Husband", ku: "مێرد", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Wife", ku: "ژن", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Cousin (Male)", ku: "خاڵۆزا", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Cousin (Male)", ku: "ئامۆزا", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Uncle (Paternal)", ku: "مام", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Aunt (Maternal)", ku: "خاڵۆژن", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Boss", ku: "سەرۆک", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Politician", ku: "سیاسەتمەدار", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Journalist", ku: "ڕۆژنامەنووس", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Waiter", ku: "خزمەتکار", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Athlete", ku: "وەرزشەوان", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Artist/Painter", ku: "هونەرمەند", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Lawyer", ku: "پارێزەر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Firefighter", ku: "ئاگرکوژێنەر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Police Officer", ku: "پۆلیس", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "King/Ruler", ku: "پاشا", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Queen", ku: "شاژن", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Crowd", ku: "قەرەباڵغی", hint: { en: "Group/Role", ku: "کۆمەڵ / ڕۆڵ" } },
      { en: "Customer", ku: "کڕیار", hint: { en: "Group/Role", ku: "کۆمەڵ / ڕۆڵ" } },
      { en: "Guest", ku: "میوان", hint: { en: "Group/Role", ku: "کۆمەڵ / ڕۆڵ" } },
      { en: "Manager", ku: "بەڕێوەبەر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Hero", ku: "پاڵەوان", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Villain", ku: "خراپەکار", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Citizen", ku: "هاووڵاتی", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Refugee", ku: "پەنابەر", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Actor", ku: "ئەکتەر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Musician", ku: "مۆسیقاژەن", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Philosopher", ku: "فەیلەسوف", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Poet", ku: "شاعیر", hint: { en: "Job/Profession", ku: "پیشە / کار" } },
      { en: "Daughter", ku: "کچ", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Son", ku: "کوڕ", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Niece/Nephew", ku: "برازا / خوشکەزا", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "Relative", ku: "خزم", hint: { en: "Person/Family", ku: "کەس / خێزان" } },
      { en: "House", ku: "خانوو", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Room", ku: "ژوور", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Door", ku: "دەرگا", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Window", ku: "پەنجەرە", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Table", ku: "مێز", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Chair", ku: "کورسی", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Bed", ku: "سیسەم", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Key", ku: "کلیل", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "City", ku: "شار", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Park", ku: "پارک", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Library", ku: "کتێبخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Kitchen", ku: "چێشتخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Garden", ku: "باخچە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Street", ku: "شەقام", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Office", ku: "ئۆفیس", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Shop/Store", ku: "دوکان", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Market", ku: "بازاڕ", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Floor (Ground)", ku: "زەوی", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Stairs", ku: "قادرمە", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Sofa/Couch", ku: "قەنەفە", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Rug/Carpet", ku: "فەرش", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Curtain", ku: "پەردە", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Pillow", ku: "سەرین", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Cabinet", ku: "کابینە", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Balcony", ku: "باڵکۆن", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Basement", ku: "ژێرزەمین", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Apartment", ku: "شوقە", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Palace", ku: "کۆشک", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Castle", ku: "قەڵا", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Tent", ku: "چادر", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Vase", ku: "گوڵدان", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Picture Frame", ku: "چوارچێوەی وێنە", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Candle", ku: "مۆم", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Hotel", ku: "هۆتێل", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Restaurant", ku: "چێشتخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Theater", ku: "شانۆ", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Stadium", ku: "یاریگا", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Mosque", ku: "مزگەوت", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Church", ku: "کەنیسە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Factory", ku: "کارگە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Attic", ku: "سەربان", hint: { en: "Place/Home", ku: "شوێن / ماڵ" } },
      { en: "Water", ku: "ئاو", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Bread", ku: "نان", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Milk", ku: "شیر", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Meat", ku: "گۆشت", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Apple", ku: "سێو", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Orange (Fruit)", ku: "پڕتەقاڵ", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Salt", ku: "خوێ", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Sugar", ku: "شەکر", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Tea", ku: "چا", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Egg", ku: "هێلکە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Rice", ku: "برنج", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Cheese", ku: "پەنیر", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Honey", ku: "هەنگوین", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Flour", ku: "ئارد", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Butter", ku: "کەرە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Cake", ku: "کێک", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Soup", ku: "شۆربا", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Grape", ku: "ترێ", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Fish (Food)", ku: "ماسی", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Vegetable", ku: "سەوزە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Chicken (Food)", ku: "گۆشتی مریشک", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Potato", ku: "پەتاتە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Tomato", ku: "تەماتە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Onion", ku: "پیاز", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Garlic", ku: "سیر", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Salad", ku: "زەڵاتە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Yogurt", ku: "ماست", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Juice", ku: "شەربەت", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Beer", ku: "بیرە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Wine", ku: "شەراب", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Chocolate", ku: "شوکولاتە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Cookie", ku: "کێکی بچووک", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Ice Cream", ku: "گولێنە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Sandwich", ku: "ساندویچ", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Pasta", ku: "پاستا", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Lemon", ku: "لیمۆ", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Banana", ku: "مۆز", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Cucumber", ku: "خەیار", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Pepper (Spice)", ku: "بیبەر", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Vinegar", ku: "سرکە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Oil (Cooking)", ku: "زەیت", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Grill/BBQ", ku: "کباب", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Dough", ku: "هەویر", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Sausage", ku: "سجوق", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Jam", ku: "مورەبا", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Syrup", ku: "شیلە", hint: { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
      { en: "Oven", ku: "فڕن", hint: { en: "Object/Item", ku: "شت / کەلوپەل" } },
      { en: "Sun", ku: "خۆر", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Moon", ku: "مانگ", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Star", ku: "ئەستێرە", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Air", ku: "هەوا", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Fire", ku: "ئاگر", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Tree", ku: "دار", hint: { en: "Nature/Plant", ku: "سروشت / ڕووەک" } },
      { en: "Flower", ku: "گوڵ", hint: { en: "Nature/Plant", ku: "سروشت / ڕووەک" } },
      { en: "Rain", ku: "باران", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Snow", ku: "بەفر", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Wind", ku: "با", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Cloud", ku: "هەور", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "River", ku: "ڕووبار", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Lake", ku: "دەریاچە", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Stone", ku: "بەرد", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Earth/Ground", ku: "زەوی", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Grass", ku: "گیا", hint: { en: "Nature/Plant", ku: "سروشت / ڕووەک" } },
      { en: "Desert", ku: "بیابان", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Fog", ku: "تەم", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Ice", ku: "بەستەڵەک", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Dust", ku: "تۆز", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Valley", ku: "دۆڵ", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Forest", ku: "دارستان", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Cave", ku: "ئەشکەوت", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Volcano", ku: "گڕکان", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Tornado", ku: "گەردەلول", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Lightning", ku: "هەورەبروسکە", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Thunder", ku: "هەورەگرمە", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Wave", ku: "شەپۆل", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Sand", ku: "خۆڵ", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Soil", ku: "خاک", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Pebble", ku: "چەو", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Island", ku: "دوورگە", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Peninsula", ku: "نیمچە دوورگە", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Swamp", ku: "زەلکاو", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Waterfall", ku: "تاڤگە", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Rainbow", ku: "پەلکەزێڕینە", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Galaxy", ku: "گەردوون", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Planet", ku: "هەسارە", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Comet", ku: "کلکدار", hint: { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
      { en: "Steam/Vapor", ku: "هەڵم", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Coal", ku: "خەڵوز", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Crystal", ku: "کریستاڵ", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Mud", ku: "قوڕ", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Petroleum", ku: "نەوت", hint: { en: "Material/Element", ku: "ماددە / توخم" } },
      { en: "Dog", ku: "سەگ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Cat", ku: "پشیلە", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Bird", ku: "باڵندە", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Cow", ku: "مانگا", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Horse", ku: "ئەسپ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Lion", ku: "شێر", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Snake", ku: "مار", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Tiger", ku: "پڵنگ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Mouse", ku: "مشک", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Sheep", ku: "مەڕ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Goat", ku: "بزن", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Chicken", ku: "مریشک", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Elephant", ku: "فیل", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Wolf", ku: "گورگ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Bear", ku: "ورچ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Rabbit", ku: "کەروێشک", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Donkey", ku: "کەر", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Spider", ku: "جاڵجاڵۆکە", hint: { en: "Animal/Insect", ku: "ئاژەڵ" } },
      { en: "Dolphin", ku: "دەڵفین", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Whale", ku: "نەهەنگ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Shark", ku: "قڕش", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Crocodile", ku: "تیمساح", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Kangaroo", ku: "کەنگەر", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Panda", ku: "پاندا", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Giraffe", ku: "زەڕافە", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Eagle", ku: "هەڵۆ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Ostrich", ku: "نەعامە", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Fox", ku: "ڕێوی", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Deer", ku: "ئاسک", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Monkey", ku: "مەیموون", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Frog", ku: "بۆق", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Turtle", ku: "کیسەڵ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Bee", ku: "هەنگ", hint: { en: "Animal/Insect", ku: "ئاژەڵ" } },
      { en: "Ant", ku: "مێروولە", hint: { en: "Animal/Insect", ku: "ئاژەڵ" } },
      { en: "Butterfly", ku: "پەپوولە", hint: { en: "Animal/Insect", ku: "ئاژەڵ" } },
      { en: "Worm", ku: "کرم", hint: { en: "Animal/Insect", ku: "ئاژەڵ" } },
      { en: "Camel", ku: "وشتر", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Pigeon", ku: "کۆتر", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Owl", ku: "کوندەپەپوو", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Penguin", ku: "بەتریق", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Hedgehog", ku: "ژیشک", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Otter", ku: "سەگاو", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Flamingo", ku: "فلامینگۆ", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Scorpion", ku: "دووپشک", hint: { en: "Animal/Insect", ku: "ئاژەڵ" } },
      { en: "Octopus", ku: "ئەختەبوت", hint: { en: "Animal", ku: "ئاژەڵ" } },
      { en: "Shakespeare", ku: "شکسپیر", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Einstein", ku: "ئاینشتاین", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Cleopatra", ku: "کلیۆپاترا", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Buddha", ku: "بوودا", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Sherlock Holmes", ku: "شێرلاک هۆڵمز", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Dracula", ku: "دراکیولا", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Genghis Khan", ku: "جەنگیزخان", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Beethoven", ku: "بیتھۆڤن", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Plato", ku: "ئەفلاتوون", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Picasso", ku: "پیکاسۆ", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Queen Elizabeth", ku: "شاژنە ئەلیزابێس", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Mickey Mouse", ku: "میکی ماوس", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Homer Simpson", ku: "هۆمەر سیمپسۆن", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Tarazan", ku: "تەڕەزان", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Newton", ku: "نیوتن", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Sahara Desert", ku: "بیابانی سەحرا", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Atlantic Ocean", ku: "زەریای ئەتڵەسی", hint: { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
      { en: "Pharaoh", ku: "فیرعەون", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "James Bond", ku: "جەیمس بۆند", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Harry Potter (Character)", ku: "هاری پۆتەر", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Nelson Mandela", ku: "نێڵسن ماندێلا", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Oprah", ku: "ئۆپرا", hint: { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
      { en: "Jack Sparrow", ku: "جاک سپارۆ", hint: { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
      { en: "Saladin", ku: "سەلاحەدین", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Nalî", ku: "نالی", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Goran", ku: "گۆران", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Mustafa Barzani", ku: "مەلا مستەفا بارزانی", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Jalal Talabani", ku: "جەلال تاڵەبانی", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Ibrahim Khalil", ku: "ئیبراھیم خەلیل", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Mala-i Jiziri", ku: "مەلای جزیری", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Cegerxwîn", ku: "جگەرخوێن", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Sherko Bekas", ku: "شێرکۆ بێکەس", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Hasan Zirek", ku: "حەسەن زیرەک", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Adnan Karim", ku: "عەدنان کەریم", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Dildar", ku: "دڵدار", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Chopy Fatah", ku: "چۆپی فەتاح", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Qazi Muhammad", ku: "قازی محەمەد", hint: { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
      { en: "Head", ku: "سەر", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Hand", ku: "دەست", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Leg", ku: "قاچ", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Eye", ku: "چاو", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Mouth", ku: "دەڤ", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Nose", ku: "لووت", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Heart", ku: "دڵ", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Stomach", ku: "گەدە", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Blood", ku: "خوێن", hint: { en: "Body Part/Substance", ku: "بەشی لەش/ماددە" } },
      { en: "Bone", ku: "ئێسک", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Sickness", ku: "نەخۆشی", hint: { en: "Health/Condition", ku: "تەندروستی/بارودۆخ" } },
      { en: "Pain", ku: "ئازار", hint: { en: "Health/Condition", ku: "تەندروستی/بارودۆخ" } },
      { en: "Medicine", ku: "دەرمان", hint: { en: "Health/Item", ku: "تەندروستی/کەلوپەل" } },
      { en: "Fever", ku: "تا", hint: { en: "Health/Condition", ku: "تەندروستی/بارودۆخ" } },
      { en: "Muscle", ku: "ماسولکە", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Skin", ku: "پێست", hint: { en: "Body Part", ku: "بەشی لەش" } },
      { en: "Shirt", ku: "کراس", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Pants", ku: "پانتۆڵ", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Dress", ku: "عەزی", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Hat", ku: "کڵاو", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Shoes", ku: "پێڵاو", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Socks", ku: "گۆرەوی", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Jacket", ku: "کۆت", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Ring", ku: "ئەنگوستیلە", hint: { en: "Accessory/Jewelry", ku: "ئامراز/زێڕینگەری" } },
      { en: "Watch", ku: "کاتژمێر", hint: { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
      { en: "Glasses", ku: "چاویلکە", hint: { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
      { en: "Bag", ku: "جانتا", hint: { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
      { en: "Belt", ku: "قایش", hint: { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
      { en: "Scarf", ku: "سروێن", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Gloves", ku: "دەستکێش", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Trousers", ku: "تڕاوسەر", hint: { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Hammer", ku: "چەکوش", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Nail", ku: "بزمار", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Screw", ku: "دەڕنەفیز", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Axe", ku: "تەور", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Scissors", ku: "مەقەست", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Rope", ku: "گوریس", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Ladder", ku: "پەیژە", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Compass", ku: "قیبلەنما", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Magnet", ku: "موگناتیس", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Battery", ku: "پاتری", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Wire", ku: "وایەر", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Microscope", ku: "مایکرۆسکۆپ", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Telescope", ku: "تەلیسکۆپ", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Scale (Weight)", ku: "تەرازوو", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Bucket", ku: "سەتڵ", hint: { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Time", ku: "کات", hint: { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Day", ku: "ڕۆژ", hint: { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Year", ku: "ساڵ", hint: { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Idea", ku: "بیرۆکە", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Truth", ku: "ڕاستی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Lie", ku: "درۆ", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Love", ku: "خۆشەویستی", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Hate", ku: "ڕق", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Hope", ku: "هیوا", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Fear", ku: "ترس", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Peace", ku: "ئاشتی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "War", ku: "شەڕ", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Freedom", ku: "ئازادی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Justice", ku: "دادپەروەری", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Rule/Law", ku: "یاسا", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "History", ku: "مێژوو", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Future", ku: "داهاتوو", hint: { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Dream", ku: "خەون", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Wisdom", ku: "زیرەکى", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Art", ku: "هونەر", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Music", ku: "مۆسیقا", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Silence", ku: "بێدەنگی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Run", ku: "ڕاکردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Sleep", ku: "خەوتن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Eat", ku: "خواردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Talk", ku: "قسەکردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Walk", ku: "ڕۆیشتن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Jump", ku: "بازدان", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Swim", ku: "مەلەکردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Write", ku: "نووسین", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Read", ku: "خوێندنەوە", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "See", ku: "بینین", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Hear", ku: "بیستن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Think", ku: "بیرکردنەوە", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Know", ku: "زانین", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Take", ku: "بردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Come", ku: "هاتن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Go", ku: "ڕۆیشتن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Cry", ku: "گریان", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Laugh", ku: "پێکەنین", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Dance", ku: "سەماکردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Sing", ku: "گۆرانی وتن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Computer", ku: "کۆمپیوتەر", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Internet", ku: "ئینتەرنێت", hint: { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
      { en: "Keyboard", ku: "کیبۆرد", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Mouse (Computer)", ku: "ماوس", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Camera", ku: "کامێرا", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Robot", ku: "ڕۆبۆت", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Screen", ku: "شاشە", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Website", ku: "ماڵپەڕ", hint: { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
      { en: "Program/App", ku: "بەرنامە", hint: { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
      { en: "Data", ku: "داتا", hint: { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
      { en: "Email", ku: "ئیمەیل", hint: { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
      { en: "Cable", ku: "کێبڵ", hint: { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
      { en: "Bank", ku: "بانک", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Museum", ku: "مۆزەخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Airport", ku: "فڕۆکەخانە", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Train Station", ku: "وێستگەی شەمەندەفەر", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Bridge", ku: "پرد", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Tunnel", ku: "تونێل", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Road", ku: "ڕێگا", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Zoo", ku: "باخچەی ئاژەڵان", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Stadium", ku: "یاریگا", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Harbor/Port", ku: "بەندەر", hint: { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
      { en: "Money", ku: "پارە", hint: { en: "Abstract Concept/Item", ku: "چەمک / دەربڕین / وشە/کەلوپەل" } },
      { en: "Wealth", ku: "سامان", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Poverty", ku: "هەژاری", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Happiness", ku: "بەختەوەری", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Sadness", ku: "خەمباری", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Anger", ku: "تووڕەیی", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Surprise", ku: "سەرسوڕمان", hint: { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
      { en: "Beauty", ku: "جوانی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Ugliness", ku: "ناشرینی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Difficulty", ku: "ناڕەحەتى", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Ease", ku: "ئاسانی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "System", ku: "سیستەم", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Religion", ku: "ئایین", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Philosophy", ku: "فەلسەفە", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Silence", ku: "بێدەنگی", hint: { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
      { en: "Cook (Action)", ku: "چێشت لێنان", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Drive", ku: "لێخوڕین", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Teach", ku: "فێرکردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Learn", ku: "فێربوون", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Buy", ku: "کڕین", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Sell", ku: "فرۆشتن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Help", ku: "یارمەتیدان", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Wait", ku: "چاوەڕێ کردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Travel", ku: "گەشتکردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Remember", ku: "بیر هێنانەوە", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Forget", ku: "لەبیر کردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Build", ku: "دروست کردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Destroy", ku: "وێران کردن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Win", ku: "بردنەوە", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Lose", ku: "دۆڕاندن", hint: { en: "Action/Verb", ku: "کردار" } },
      { en: "Beautiful", ku: "جوان", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Ugly", ku: "ناشرین", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Fast", ku: "خێرا", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Slow", ku: "هێواش", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "High", ku: "بەرز", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Low", ku: "نزم", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Empty", ku: "بەتاڵ", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Full", ku: "پڕ", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Rich", ku: "دەوڵەمەند", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Poor", ku: "هەژار", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Happy", ku: "دڵخۆش", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Sad", ku: "خەمبار", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Angry", ku: "تووڕە", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "New", ku: "نوێ", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Old", ku: "کۆن", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Loud", ku: "بەرز (دەنگ)", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Quiet", ku: "هێمن", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Strong", ku: "بەهێز", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Weak", ku: "لاواز", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Big", ku: "گەورە", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Small", ku: "بچووک", hint: { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
      { en: "Laptop", ku: "لابتۆپ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Backpack", ku: "جانتا", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Flashlight", ku: "لایت", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Mirror", ku: "ئاوێنە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Umbrella", ku: "چەتر", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Toothbrush", ku: "فڵچەى ددان", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Suitcase", ku: "عەلاگە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Perfume", ku: "عطر - بۆن", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Keycard", ku: "کارتى بانک", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Helmet", ku: "سەرپۆش - لەچک", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Lantern", ku: "چرا", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Globe", ku: "نەخشەی جیهان", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Map", ku: "نەخشە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Album", ku: "ئەلبوم", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Thermos", ku: "تەرمۆزە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Headphones", ku: "سەماعە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Microphone", ku: "مایکروفۆن", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Printer", ku: "پرینتەرو", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Scanner", ku: "سکانەر", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Projector", ku: "پرۆجێکتۆر - داتاشۆ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Calculator", ku: "حاسیبە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Stapler", ku: "کابیسە - مەکینەى دەرزى", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Fire extinguisher", ku: "ئاگرکوژێنەرەوە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Shovel", ku: "پاچ - چاڵ هەڵکەنە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Drill", ku: "دڕێڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Paintbrush", ku: "فڵچەى بۆیاخ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Bucket lid", ku: "سەرى سەتڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Mixer", ku: "میکسەر", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Alarm clock", ku: "کاتژمێری دیوار", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Nightstand", ku: "عەلاگەى جل", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Bookshelf", ku: "کتێبخانە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Charger", ku: "شەحنى مۆبایل", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "SIM card", ku: "سیمکارت", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Joystick", ku: "گێڕى سەیارە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Game console", ku: "پلەیستەیشن", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Puzzle", ku: "مەتەڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Board", ku: "تەختە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Whistle", ku: "فیکە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Shootgun", ku: "تاپڕ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Nut", ku: "گوێز", hint: { en: "Objects/Things", ku: "خواردن" } },
      { en: "Golden Great Wall of China", ku: "شورای چین", hint: { en: "Objects/Things", ku: "شوێن / بینا" } },
      { en: "Hidden Heel", ku: "Hidden پاشدەنگ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "East Bison", ku: "گامێش", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Old SpongeBob SquarePants", ku: "سپۆنجبۆب", hint: { en: "Objects/Things", ku: "کارتۆن" } },
      { en: "Sacred Roundabout", ku: "گەڕەک", hint: { en: "Objects/Things", ku: "شوێن" } },
      { en: "Ancient Historical museum", ku: "مۆزەخانە", hint: { en: "Objects/Things", ku: "شوێن / بینا" } },
      { en: "New Monument", ku: "پەیکەر", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Avocado", ku: "ئاڤۆکادۆ", hint: { en: "Objects/Things", ku: "خواردن / میوە" } },
      { en: "Royal Fountain", ku: "کۆڵنج‌", hint: { en: "Objects/Things", ku: "ئەندامى لەش" } },
      { en: "Modern Geyser", ku: "گیزەرى ئاو", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Golden Bench vise", ku: "گێزەر", hint: { en: "Objects/Things", ku: "خواردن / میوە" } },
      { en: "South Aurora", ku: "قەیسى", hint: { en: "Objects/Things", ku: "خواردن میوە" } },
      { en: "Sacred Kidney", ku: "شمشاڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Little Loafers", ku: "دەهۆڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Sacred Cyclone", ku: "تەپڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Grand Lung", ku: "دەف", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Ancient Superman", ku: "سوپەرمان", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Little Saz", ku: "سپایدەرمان", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Twin Customs", ku: "باتمان", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Sacred Bulgur", ku: "تەڕەزان", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Ancient Bullet train", ku: "شمشێر", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "South Daenerys Targaryen", ku: "هۆڵک", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Grand Parking lot", ku: "میکیماوس", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Little Charger", ku: "تۆم و جێری", hint: { en: "Objects/Things", ku: "کارتۆن" } },
      { en: "South Weasel", ku: "سبەیستوون", hint: { en: "Objects/Things", ku: "پەخش" } },
      { en: "Old Popeye", ku: "کینگ کۆنگ", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Crystal Adapter", ku: "هۆنگ کۆنگ", hint: { en: "Objects/Things", ku: "شوێن" } },
      { en: "East Hummingbird", ku: "محمد", hint: { en: "Objects/Things", ku: "کەس" } },
      { en: "Modern Wonder Woman", ku: "ماهیر حسن", hint: { en: "Objects/Things", ku: "ئەکتەر" } },
      { en: "Hidden Kurdistan Museum", ku: "ئەحمەد جۆڵا", hint: { en: "Objects/Things", ku: "ئەکتەر" } },
      { en: "Modern Highway interchange", ku: "گوێرەکە", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Twin Black hole", ku: "دووانە", hint: { en: "Objects/Things", ku: "کەس" } },
      { en: "Hidden Reservoir", ku: "خاو و خلیچک", hint: { en: "Objects/Things", ku: "وەسف / کردار" } },
      { en: "Royal Dock", ku: "شاهانە", hint: { en: "Objects/Things", ku: "وەسف / کەس" } },
      { en: "South Mulan", ku: "مستەر بین", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Ancient Camera", ku: "جۆکەر", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "West Clarinet", ku: "یاری مۆنۆپۆلی", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Silver Drill", ku: "یاری هەلوکێن", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "West Retina", ku: "یاری ئۆکەی", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Twin Lantern", ku: "یاری تاوڵە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Blue Gnocchi", ku: "یاری دۆمینە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Twin Apogee", ku: "یاری هەڵماتێن", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Modern Petra", ku: "یاری چاوشارکێ", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Ancient Elbow", ku: "یاری دوگۆڵی", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Blue Wrist", ku: "یاری مار و پەیژە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Little Violin", ku: "یاری چاڵ چاڵێن", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Golden Polenta", ku: "یاری باسکە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Blue Tapir", ku: "یاری تێنس", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Twin Binoculars", ku: "یاری بالە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Hidden Hemisphere", ku: "یاری فڕیوە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "South Santur", ku: "کارتۆنی سەنافر", hint: { en: "Objects/Things", ku: "کارتۆن" } },
      { en: "Golden Sports complex", ku: "کآس - جامی ئاڵتوون", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "North Hijab", ku: "سرکە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Blue Citadel", ku: "هەنگ", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "East Grape molasses", ku: "باکوور", hint: { en: "Objects/Things", ku: "شوێن / ئاڕاستە" } },
      { en: "Hidden Oyster", ku: "باشوور", hint: { en: "Objects/Things", ku: "شوێن / ئاڕاستە" } },
      { en: "Crystal Taj Mahal", ku: "هیندستان", hint: { en: "Objects/Things", ku: "شوێن" } },
      { en: "Blue Plateau", ku: "فاسۆلیا", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Nebula", ku: "نەخۆشی کۆلێرا", hint: { en: "Objects/Things", ku: "لەش / تەندروستی" } },
      { en: "North Glacier", ku: "نەخۆشی سیل", hint: { en: "Objects/Things", ku: "لەش / تەندروستی" } },
      { en: "Silver Mayonnaise", ku: "نەخۆشی سەڕەتان", hint: { en: "Objects/Things", ku: "لەش / تەندروستی" } },
      { en: "Hidden Memorial", ku: "نەخۆشی پەتا", hint: { en: "Objects/Things", ku: "لەش / تەندروستی" } },
      { en: "Modern Weasel", ku: "نەخۆشی ئایدز", hint: { en: "Objects/Things", ku: "لەش / تەندروستی" } },
      { en: "Blue Minivan", ku: "کولێرە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Little Oud", ku: "سەموون", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Modern Simba", ku: "ناوساجی", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Modern Map", ku: "ناوشکێنە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Modern Fire extinguisher", ku: "کولیچە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Little Simit", ku: "نانی تیری", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Old Lung", ku: "نانی هەورامی", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Modern Luke Skywalker", ku: "یاری وەرەقە - کارت", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Hidden Apogee", ku: "یاری دامە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "North Flashlight", ku: "یاری کڵاو کڵاوێن", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "North Bridge", ku: "جێنێراڵ", hint: { en: "Objects/Things", ku: "کار/ پۆست" } },
      { en: "Old Joystick", ku: "یاری ماینکرافت", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Golden Lynx", ku: "یاری گاد ئۆف واڕ", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Twin Sloth", ku: "یاری پەبجی", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "West Wombat", ku: "یاری کرمەکە - مۆبایل", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "West Stonehenge", ku: "یاری سان ئەندریەس - سانادرێس", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Grand Lantern", ku: "یاری ماریۆ", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Golden Retina", ku: "یاری کڕاش", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Blue Pomegranate", ku: "یاری زۆرانبازی - موصارەعە", hint: { en: "Objects/Things", ku: "یاری" } },
      { en: "Old Wheelbarrow", ku: "جووت بون - سێکس", hint: { en: "Objects/Things", ku: "کار / هەست" } },
      { en: "Silver Greenhouse", ku: "ڕۆمانسیەت", hint: { en: "Objects/Things", ku: "کار / هەست" } },
      { en: "East Helmet", ku: "ڤالانتاین", hint: { en: "Objects/Things", ku: "کات / هەست" } },
      { en: "Old Liver", ku: "بوک و زاوا", hint: { en: "Objects/Things", ku: "کەس" } },
      { en: "Grand Sea turtle", ku: "لینجی", hint: { en: "Objects/Things", ku: "مادە" } },
      { en: "South Fitness tracker", ku: "ئیندۆمی", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Twin Submarine", ku: "بیبسی", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "East Oatmeal", ku: "کۆکاکۆلا", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Royal Hummingbird", ku: "دۆ", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "East Playground", ku: "یاپراخ - دۆڵمە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Modern Tram", ku: "شفتە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Golden Fire extinguisher", ku: "کفتە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "West Quasar", ku: "تەڕەساس - خواردنێکی کوردیە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Royal Yoda", ku: "تەڕەماش - خواردنێکی کوردیە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Control tower", ku: "ماش - خواردنێکی کوردیە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Old Router (wood)", ku: "نۆکاو - خواردنێکی کوردیە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Hidden Highway interchange", ku: "ترخێنە - خواردنێکی کوردیە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Grand Mastaw", ku: "ماستاو", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "East Recreation center", ku: "دۆینە - خواردنێکی کوردیە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Crystal Oatmeal", ku: "ڕێواس", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "East Monument", ku: "شلیک", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "West Heel", ku: "شوتی", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "West Yacht", ku: "کاڵەک", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Megaphone", ku: "کولەکە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Blue Monument", ku: "ستیان", hint: { en: "Objects/Things", ku: "جل و بەرگ" } },
      { en: "Hidden Oud", ku: "پەڵپینە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Crystal Helmet", ku: "نیسکێنە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Little Tailor shop", ku: "باسترمە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Grand Porcupine", ku: "فینگەر - پەتاتەی قاشکراو", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Backpack", ku: "شاورمە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Pressure washer", ku: "پاقلە", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Crystal E-reader", ku: "مەعکەرۆنی", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Twin Smoke detector", ku: "پاستا", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "East Community center", ku: "چەوەنەر", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Modern Chestnut", ku: "بیبەری توون", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "South Fountain square", ku: "بیبەری شیرین", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "North Blender", ku: "خەیار", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "East Clarinet", ku: "کەرەوز", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Little Tofu", ku: "مەعدەنوس", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Sports complex", ku: "نەعنا", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Golden Cumin", ku: "زەعتەر", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Ancient SUV", ku: "کەوەر", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Hidden Equator", ku: "گۆڵ", hint: { en: "Objects/Things", ku: "شوێن" } },
      { en: "West Batman", ku: "تمەنی ئێرانی", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Golden Nightstand", ku: "دینار", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Crystal Projector", ku: "دۆلار", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Blue Mink", ku: "یۆرۆ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Blue Turban", ku: "پسکیت", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Sacred Sourdough", ku: "جبس", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "West Hydraulic jack", ku: "مۆتا", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "West Submarine", ku: "لێسانەوە", hint: { en: "Objects/Things", ku: "کردار" } },
      { en: "Blue Accordion", ku: "قاشکردن", hint: { en: "Objects/Things", ku: "کردار" } },
      { en: "Modern Sumac", ku: "مەمکەکان", hint: { en: "Objects/Things", ku: "ئەندامی جەستە" } },
      { en: "Old Toll booth", ku: "چۆلەکە", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Modern Studio apartment", ku: "مارمێلکە", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Golden Optimus Prime", ku: "ژیشک", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Modern Kubba", ku: "قالۆنچە", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Grand Clams", ku: "جاڵجاڵۆکە", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "East Water treatment plant", ku: "کۆتری کوکوختی", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Twin Ketchup", ku: "باڵندەی کەناری", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Ancient Hummingbird", ku: "فیل", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Royal Granola", ku: "ئاژەڵی کوالا", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Ancient Paint sprayer", ku: "مەیموون", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "New Hummingbird", ku: "پڵنگ", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Silver Router", ku: "داڵ", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Silver Polenta", ku: "حوشتر", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Grand Stoat", ku: "هەڵۆ", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Grand Scallop", ku: "قڕژاڵ", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Royal Mink", ku: "ڕۆبیان", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Ancient Tapir", ku: "گوێچکە ماسی", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "South Wildebeest", ku: "ئەستێرەی دەریا", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "South Clove", ku: "ئەسپی دەریا", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Hidden Alarm clock", ku: "مار", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Royal Iron Man", ku: "ماری کۆبرا", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Little Bridge", ku: "ماری ئەناکۆندا", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Golden Tracksuit", ku: "کەرە کێوی", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Hidden Geyser", ku: "هێستر", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Twin Oatmeal", ku: "تەور", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Twin Pomegranate", ku: "تەپڵەک", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Golden Savanna", ku: "وڵاخ", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Sacred Walnut", ku: "شێر", hint: { en: "Objects/Things", ku: "ئاژەڵ" } },
      { en: "Hidden Tram", ku: "کەوگیر", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Ancient Polenta", ku: "کەوچک", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Twin Streetcar", ku: "چەتاڵ", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Twin Walnut", ku: "کەرە - خواردن", hint: { en: "Objects/Things", ku: "خواردن / خواردنەوە" } },
      { en: "Little Album", ku: "ئینجانە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Twin Minivan", ku: "کلیل", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Royal Toll booth", ku: "پلاکی کارەبا", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Little Aurora", ku: "تەوالێت", hint: { en: "Objects/Things", ku: "شوێن / بینا" } },
      { en: "Royal Oasis", ku: "خولە پیزە", hint: { en: "Objects/Things", ku: "کارەکتەر" } },
      { en: "Old Carpet shop", ku: "زنجیر", hint: { en: "Objects/Things", ku: "جل و بەرگ" } },
      { en: "Royal Hemisphere", ku: "قۆپچە", hint: { en: "Objects/Things", ku: "جل و بەرگ" } },
      { en: "Silver Skyscraper", ku: "بەکرە - دەزو", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Old Space station", ku: "مقەست", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Silver Ankle", ku: "کرێمی دەست", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Old Blazer", ku: "شانە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "South Vest", ku: "موجەفیفە - وشک کەرەوە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Blue Lentils", ku: "ئوتو", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Royal Couscous", ku: "پەیژە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Modern AR glasses", ku: "سەبەتە", hint: { en: "Objects/Things", ku: "شت / کەلوپەل" } },
      { en: "Bus stop", ku: "وەستانگەی ئەتۆمی", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Train station", ku: "کارگە", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Subway station", ku: "ژێرزەمین", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Pier", ku: "سەربان", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Lighthouse", ku: "تاسەی شەقام", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Opera House", ku: "خانەی بەساڵاچوان", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Observatory", ku: "سینەما", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Greenhouse", ku: "هۆڵی کۆبونەوە", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Warehouse", ku: "کەپر", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Airport terminal", ku: "فڕۆکەخانە", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Customs", ku: "گومرگ", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Carpet shop", ku: "دوکانی فەرش", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Studio apartment", ku: "ستۆدیۆ", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Citadel", ku: "گەڕەک", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Villa", ku: "ڤێلا", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Villa", ku: "کۆشک / قەڵا", hint: { en: "Places/Buildings/Furniture", ku: "شوێن / باڵەخانە" } },
      { en: "Biryani", ku: "بریانی", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Mastaw", ku: "برنج", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Tea with cardamom", ku: "چا", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Tahini", ku: "هەڵوژە", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Sumac", ku: "لەتکە نۆک", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Pomegranate", ku: "مێوژ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Okra", ku: "بامێ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Lentils", ku: "شەربەت", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Chickpeas", ku: "ترۆزی", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Bulgur", ku: "کێوی", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Flatbread", ku: "قەڕنابیت", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Baklava", ku: "کەلەرم", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Simit", ku: "برمە", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Pide", ku: "پاقلاوە‌", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Grape molasses", ku: "قاوە", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Sour cherry", ku: "شیر", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Apricot", ku: "کاکاو", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Quince", ku: "پیکیپاودەر / بەیکن باودر", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Sesame", ku: "هەنجیر", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Coriander", ku: "هەنار", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Cumin", ku: "ترێ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Clove", ku: "خورما", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Cardamom", ku: "مۆز", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Turmeric", ku: "ئەنەناس", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Cinnamon", ku: "لالەنگی / خۆشداکەنە", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Coconut", ku: "شەکر", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Avocado", ku: "ئاڤۆگادۆ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Almond", ku: "بادام / بادەم", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Walnut", ku: "گوێز", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Pistachio", ku: "گەنم", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Cashew", ku: "جۆ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Soy sauce", ku: "فستق", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Mayonnaise", ku: "مایۆنێز", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Ketchup", ku: "کەتچەپ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Mustard", ku: "ماستەرد", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Salsa", ku: "بلوبێری", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Tofu", ku: "سەروپێ / پاچە", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Edamame", ku: "قەزوان", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Granola", ku: "گۆیژ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Oatmeal", ku: "قۆخ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Couscous", ku: "لیمۆ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Polenta", ku: "پڕتەقاڵ", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Sourdough", ku: "سندی", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Bruschetta", ku: "کێوی / میوەی کیوی", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Ravioli", ku: "دراگۆن فروت", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Gnocchi", ku: "توتڕک / توتی سور", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Mussels", ku: "توو / جۆرێکە لە میوەی بێری", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Clams", ku: "شاتوو", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Oyster", ku: "گەڵامێو", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Scallop", ku: "لیمەندۆزی", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Calamari", ku: "کالیار", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Saffron", ku: "برنجی سور", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Vanilla", ku: "سێو", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Maple syrup", ku: "بەڕو", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Chestnut", ku: "چوالە", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Basil", ku: "ڕیواس", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Parsley", ku: "شلیک", hint: { en: "Food/Drink/Ingredients", ku: "خواردن / خواردنەوە" } },
      { en: "Aurora", ku: "شەونمی بەیان", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Glacier", ku: "تەم و مژ", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Permafrost", ku: "بەفر", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Oasis", ku: "باران", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Estuary", ku: "خۆڵبارین", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Mangrove", ku: "زریان", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Coral reef", ku: "بومەلەرزە", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Atoll", ku: "تیشکی خۆر", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Fjord", ku: "خۆر", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Geyser", ku: "مانگ", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Lagoon", ku: "مەریخ", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Plateau", ku: "هێزی کێشکردنی زەوی", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Savanna", ku: "زەوی", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Steppe", ku: "دەشت", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Taiga", ku: "گرد", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Monsoon", ku: "شاخ", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Hurricane", ku: "دۆڵ", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Cyclone", ku: "تاڤگە", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Wildfire", ku: "ڕەز", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Drought", ku: "باخچە", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Perigee", ku: "مانگی هیلالی", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Apogee", ku: "تەرزە", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Nebula", ku: "هەورە گرمە", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Quasar", ku: "هەورە بروسکە", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Black hole", ku: "سەهۆڵبەندان", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Meteor", ku: "ئەشکەوت", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Space station", ku: "کەنار ئاو", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Orbit", ku: "ڕوبار", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Equator", ku: "دەریا", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Hemisphere", ku: "هەور", hint: { en: "Nature/Weather/Space", ku: "سروشت / کەشوهەوا" } },
      { en: "Hummingbird", ku: "داینەسوڕ / دەنگەسوڕ", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Armadillo", ku: "مارمێلکە", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Sloth", ku: "کرمە لیقە", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Meerkat", ku: "خاڵخاڵۆکە", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Ibex", ku: "چەقەڵ", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Bison", ku: "کەمتیار", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Wildebeest", ku: "ورچ", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Hyena", ku: "بەتریق", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Mole", ku: "پشیلەی کێوی", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Badger", ku: "قەل / عەلەشیش", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Porcupine", ku: "قاز", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Macaque", ku: "مراوی", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Lemur", ku: "پۆڕ / جۆرێکە لە باڵندە", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Tapir", ku: "ژیژک", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Aardvark", ku: "سالە قن سور / جۆرێکە لە مەیمون", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Wombat", ku: "زەڕافە", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Lynx", ku: "فیل", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Mink", ku: "مشک", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Stoat", ku: "جرج", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Weasel", ku: "ڕاکۆن / راکون", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Sea turtle", ku: "توتی", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Manatee", ku: "پەری دەریا", hint: { en: "Animals/Insects", ku: "ئەفسانەیی / کارەکتەر" } },
      { en: "Beluga", ku: "قڕش", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Swordfish", ku: "هەشت پێ", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Barracuda", ku: "هەزارپێ", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Hedgehog local", ku: "ئاسک", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Kingfisher", ku: "بەراز", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Albatross", ku: "مانگا", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Pelican", ku: "شەمشەمەکێرە", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Cormorant", ku: "کونەپەپوو", hint: { en: "Animals/Insects", ku: "ئاژەڵ" } },
      { en: "Sherwood Forest (Robin Hood)", ku: "ڕۆبن هۆد", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "Wonder Woman", ku: "ئەکتەر ئارنۆڵد", hint: { en: "Famous/Fictional Figures", ku: "ئەکتەر" } },
      { en: "Iron Man", ku: "ئەکتەر ڤاندام", hint: { en: "Famous/Fictional Figures", ku: "ئەکتەر" } },
      { en: "Batman", ku: "مامە ڤاندام", hint: { en: "Famous/Fictional Figures", ku: "کەس / بەناوبانگ" } },
      { en: "Superman", ku: "بلە خەمبار", hint: { en: "Famous/Fictional Figures", ku: "کەس / بەناوبانگ" } },
      { en: "Spiderman", ku: "کامەران عومەر", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Luke Skywalker", ku: "عەزیز وەیسی", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Darth Vader", ku: "سامان عومەر", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Yoda", ku: "جەستن بیبەر", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Frodo Baggins", ku: "حەسەن زیرەک", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Gandalf", ku: "مورتەزا پاشایی", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Katniss Everdeen", ku: "خالید ڕامبۆ", hint: { en: "Famous/Fictional Figures", ku: "گۆرانیبێژ" } },
      { en: "Daenerys Targaryen", ku: "ڕامبۆ", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "Tyrion Lannister", ku: "جاکیشان", hint: { en: "Famous/Fictional Figures", ku: "ئەکتەر" } },
      { en: "Jon Snow", ku: "گلندایزەر", hint: { en: "Famous/Fictional Figures", ku: "کارتۆن" } },
      { en: "Optimus Prime", ku: "عدنان و لینا", hint: { en: "Famous/Fictional Figures", ku: "کارتۆن" } },
      { en: "Mulan", ku: "کۆنان", hint: { en: "Famous/Fictional Figures", ku: "کارتۆن" } },
      { en: "Aladdin", ku: "عەلادین", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "Simba", ku: "سیمبا", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "Naruto", ku: "ناروتۆ", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "SpongeBob SquarePants", ku: "سپۆنجبۆب", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "Dora the Explorer", ku: "دۆرا / کارتۆن", hint: { en: "Famous/Fictional Figures", ku: "کارەکتەر" } },
      { en: "Throat", ku: "قوڕگ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Ankle", ku: "ئەژنۆ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Wrist", ku: "سنگ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Elbow", ku: "لێو", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Heel", ku: "برژانگ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Nape", ku: "برۆ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Palm", ku: "دەست", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Pupil (eye)", ku: "چاو", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Retina", ku: "ناوچەوان", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Ligament", ku: "گوێ / گوێکان", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Tendon", ku: "پاژنە / پاژنەی پێ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Incisor", ku: "گورچیلە", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Molar", ku: "ڕیخۆڵە", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Appendix", ku: "دڵ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Liver", ku: "جەرگ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Kidney", ku: "زمان", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Lung", ku: "لوت", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Thyroid", ku: "نینۆک", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "دەمار", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "مێشک", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "خوێن", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "ڕان", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "ماسولکە / عەزەڵات", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "قژ", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "موو / توک", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "ورگ / سک", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "سیەکان", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "موی لوت", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Gallbladder", ku: "گوپ / ڕومەت", hint: { en: "Body Parts & Health", ku: "بەشی لەش / تەندروستی" } },
      { en: "Hijab", ku: "عەبا", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Keffiyeh", ku: "کەپی گوێ", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Abaya", ku: "نیقاب", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Thawb", ku: "ماکسی", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Sherwani", ku: "شەرواڵ", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Kurta", ku: "کورتان", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Vest", ku: "چاکەتی گولە نەبڕ", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Blazer", ku: "ملپێچ", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Cardigan", ku: "دەستکێش", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Tracksuit", ku: "تراکسود", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Flip-flops", ku: "نەعل", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Loafers", ku: "قۆنەرە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Sneakers", ku: "کڵاش", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Turban", ku: "تەزبیح", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "بەنەخوێن", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "بیجامە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "فانیلە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "گۆرەوی", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "لۆکە / پەموو", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "دایبی", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "بەروانکە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "جامانە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "قەمسەڵە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "جزمە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "کالە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "پەڕۆ", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "ملوانکە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "بازنی دەست", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "گوارە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "ئەڵقە / مستیلە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "گۆبەرۆک", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "ملە لیرە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Beret", ku: "جزداشە", hint: { en: "Clothing & Accessories", ku: "جلوبەرگ/کەلوپەل" } },
      { en: "Lathe", ku: "پلایس", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Bench vise", ku: "بزمار", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "C-clamp", ku: "گسکی کارەبایی", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Router (wood)", ku: "پەرداخ", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Soldering iron", ku: "جەقۆ", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Multimeter", ku: "کۆنتڕۆڵ", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Oscilloscope", ku: "تەلەفزیۆن", hint: { en: "Tools & Equipment", ku: "ئامێر/کەرەستە" } },
      { en: "Hydraulic jack", ku: "ڕادیۆ", hint: { en: "Tools & Equipment", ku: "ئامێر/کەرەستە" } },
      { en: "Chainsaw", ku: "چێینساو", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Angle grinder", ku: "چەکوش", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Paint sprayer", ku: "ئیسپانە", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Pressure washer", ku: "مەنجەڵ", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Hand drill", ku: "دۆلکەی ئاو", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Hand drill", ku: "بەڕادی ئاو", hint: { en: "Tools & Equipment", ku: "ئامێر/کەرەستە" } },
      { en: "Hand drill", ku: "فەرش", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Hand drill", ku: "کومبار", hint: { en: "Tools & Equipment", ku: "ئامراز/کەرەستە" } },
      { en: "Dam", ku: "بەنداو", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Reservoir", ku: "ساحەی دوگۆڵی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Irrigation canal", ku: "مەحکەمە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Seaport", ku: "زیندان", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Freight terminal", ku: "گەراجی ئوتومبێل", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Highway interchange", ku: "بینای شارەوانی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Toll booth", ku: "بورجی ئیڤڵ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Rail yard", ku: "هەڕەمەکانی میسڕ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "قاوەخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "قەسابخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ڕیستۆرانت", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سەمونخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "نانەواخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "مارکێت", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سوپەرمارکێت", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دوکانی سەرچاکردن / دەلاک", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "چاخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "کەبابخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "مەزادخانەکە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ئوتێل", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "تەکێ / میوانخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "بنکەی پۆلیس", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "زانکۆ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "قوتابخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ئارایشتگە / ساڵۆن", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دەرمانخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "نەخۆشخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "قونسوڵخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دەواجن", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سایلۆ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سلێمانی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "هەولێر", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دهۆک", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "هەڵەبجە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "نیویۆڕک", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "پەیکەری ئاشتی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "تۆکیۆ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ئیستەنبوڵ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ممەکە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ڕوباری نیل", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دەریاچەی دوکان", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "هەورامان", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "کرماشان", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "تاران", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "پێنجوێن", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "چوارتا", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سیتەک", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سەهۆڵەکە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "باخی غشتی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "پارکی ئازادی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دارەسوتاوەکە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "کۆشکی سپی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "قەڵای هەولێر", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "پردی دەلال", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "باوەگوڕگوڕ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "میسڕ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ڕوسیا", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "چین", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "کۆریای باکور/باشور", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "فەڕەنسا", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سەری ڕەش / هەولێر", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سابونکەران", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دارستانی ئەمازۆن", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "بەڕازیل", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "سعودیە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "تورکیا", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ئەشکەوتی هەزارمێرد", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "ئەشکەوتی شانەدەر", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "بورجی خەلیفە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "دوبەی", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "گەلی عەلیبەگ", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "شاخی کۆڕەک", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "پەرلەمان", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Logistics hub", ku: "کتێبخانە", hint: { en: "Places & Infrastructure", ku: "شوێن / باڵەخانە" } },
      { en: "Tram", ku: "شڕێک", hint: { en: "Vehicles & Transport", ku: "کارتۆن / کارەکتەر" } },
      { en: "Streetcar", ku: "فیۆنا لە کەرتۆنی شڕێک", hint: { en: "Vehicles & Transport", ku: "کارەکتەر" } },
      { en: "Ferry", ku: "گوڵدان", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Yacht", ku: "کورسی", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Submarine", ku: "قەنەفە", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Scooter (electric)", ku: "زۆپا / گەرمکەرەوە", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Minivan", ku: "هیتەر / گەرمکەرەوە", hint: { en: "Vehicles & Transport", ku: "ئامێر" } },
      { en: "SUV", ku: "پانکە / فێنککەرەوە", hint: { en: "Vehicles & Transport", ku: "ئامێر" } },
      { en: "Rickshaw", ku: "موبەریدە / فێنککەرەوە", hint: { en: "Vehicles & Transport", ku: "ئامێر" } },
      { en: "Tuk-tuk", ku: "بەتانی", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Bullet train", ku: "سەرین", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Cable car", ku: "بۆیەی نینۆک", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Monorail", ku: "موکێش", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Hovercraft", ku: "ئاوێنە", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Hovercraft", ku: "سەماوەر", hint: { en: "Vehicles & Transport", ku: "شت / کەلوپەل" } },
      { en: "Smartphone", ku: "تەلەفۆن - مۆبایل", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "E-reader", ku: "مەکینەی ڕیشتاشین", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "Smartwatch", ku: "کاتژمێری دەستی", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "Drone", ku: "درۆن", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "3D printer", ku: "فڵچەی دەم و ددان", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "VR headset", ku: "مەعجونی دەم و ددان", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "AR glasses", ku: "نینۆکەر", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "Smart speaker", ku: "دەسشۆر - مەخسەل", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "Fitness tracker", ku: "خاولی", hint: { en: "Technology & Devices", ku: "شت / کەلوپەل" } },
      { en: "Saz", ku: "ساز - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Daf", ku: "پیانۆ - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Oud", ku: "عود - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Tambourine", ku: "کەمان - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Santur", ku: "سەنتور - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Violin", ku: "گیتار - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Cello", ku: "زەنگۆڵە", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Clarinet", ku: "کلارینێت - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } },
      { en: "Accordion", ku: "فلووت - ئامێری مۆسیقا", hint: { en: "Music & Instruments", ku: "شت / کەلوپەل" } }
];

// Export for use in index.html
// For browser compatibility, attach to window if needed
if (typeof window !== 'undefined') {
  window.wordDatabase = wordDatabase;
}
